blog/urls.py
from django.conf.urls import url, handler404

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
]

handler404 = "blog.views.page_not_found"

templates/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %} {% endblock %} </title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="keywords" content="ihades,斯人也,python,java,c++">
    <meta name="description" content="ihades斯人也博客">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="{% static 'blog/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113889298-1"></script>
    <!-- Google adsense -->
    <script data-ad-client="pub-5761483021845281" 
    async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-113889298-1');
    </script>
    <link rel="icon" href="{% static 'favicon.png'%}">
    <style>
        span.highlighted {
            color: red;
        }
    </style>


</head>

<body>
    <div class="container">

        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="{% url 'blog:index' %}"><b>// 斯 人 也 </a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                                <li class="cl-effect-11"><a href="https://github.com/GeekHades1"
                                        data-hover="GitHub">GitHub</a></li>
                                <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于我">关于我</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#">
                            <span id="search-icon" class="ion-ios-search-strong"></span>
                        </a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                                <input type="search" name="q" placeholder="搜索" required>
                                <button type="submit"><span class="ion-ios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div><!-- col-md-8 -->
            </div>
            <!-- page-title -->
            <br>
            <!-- typing__module -->
            <div class="typing__module page-title__title">

                <div class="typed-strings">
                    {% get_slogans as slogans %}
                    {% for slogan in slogans %}
                    <span>{{ slogan.content }}</span>
                    {% empty %}
                    <span>I am hades(斯人也), Welcome you to view my website.</span>
                    {% endfor %}
                    <!-- <span>I am hades(斯人也).Welcome you to view my website.</span>
                    <span>I am a Programmer.</span>
                    <span>I am dedicated to Data Analytics currently.</span>
                    <span>The About Me page has more information about me.</span> -->
                </div><span class="typed"></span>

            </div><!-- End / typing__module -->
        </header>
    </div>
    <div class="copyrights">Power by <a href="https://ihades.cn">GeekHades</a></div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block main %}
                    {% endblock main %}
                </main>
                <aside class="col-md-4">
                    {% block toc %}
                    {% endblock toc %}
                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">最多人看</h3>
                        {% get_hotest_posts as recent_post_list %}
                        <ul>
                            {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                            {% empty %}
                            暂无文章！
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title" style="color: crimson">**优惠券**</h3>
                        {% get_offer_link as offer_links %}
                        <ul>
                            {% for offer_link in offer_links %}
                            <li>
                                <a href="{{ offer_link.link }}" target="_blank">{{ offer_link.name }} </a>
                            </li>
                            {% empty %}
                            暂无优惠券！
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">Tags</h3>
                        {% get_tags as tag_list %}
                        <ul>
                            {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                            </li>
                            {% empty %}
                            暂无标签！
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">学习资源网站推荐</h3>
                        {% get_friendly as sw_list %}
                        <ul>
                            {% for ShareWeb in sw_list %}
                            <li>
                                <a href="{{ ShareWeb.link}}" target="_blank">{{ ShareWeb.name }}</a>
                            </li>
                            {% empty %}
                            暂无标签！
                            {% endfor %}
                        </ul>
                    </div>



                    <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                <p class="copyright">Hades © 2018-2019
            
                   <br>
                   
 		    <a href="http://www.miitbeian.gov.cn" title="备案" target="_blank">粤ICP备17133260号-1</a>
                 </p>
               

                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="https://github.com/GeekHades1">GitHub</a></li>
                <li><a href="{% url 'blog:about' %}">关于我</a></li>
            </ul>
        </nav>
    </div>

    <!-- js -->
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/script.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <!-- <script  src="{% static 'blog/js/countUp.js' %}"></script> -->
    <script src="{% static 'blog/js/custom.js' %}"></script>


</body>

</html>